// Command adr-index writes the index page of the decision records.
//
// The records themselves are the pages the site renders; only the list of
// them is generated, so it cannot leave one out or name one that is gone.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/vriesdemichael/bitbucket-data-center-cli/internal/adr"
)

func main() {
	directory := flag.String("dir", adr.Directory, "Directory holding the decision records")
	flag.Parse()

	if err := writeIndex(*directory); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func writeIndex(directory string) error {
	records, err := adr.Load(directory)
	if err != nil {
		return err
	}

	path := filepath.Join(directory, "index.md")
	if err := os.WriteFile(path, []byte(renderIndex(records)), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	fmt.Printf("wrote %s (%d records)\n", path, len(records))

	return nil
}

func renderIndex(records []adr.Record) string {
	var out strings.Builder

	out.WriteString("---\n# Generated by `task docs:export-adr-index` from the records in this directory. Do not edit.\n---\n\n")
	out.WriteString("# Decision Records\n\n")
	out.WriteString("How this project is built and worked on, one rule to a record. Each record says what holds and why, ")
	out.WriteString("and the alternatives it turned down.\n\n")

	for _, record := range records {
		fmt.Fprintf(&out, "- [ADR-%03d: %s](%s)\n", record.Number, record.Title, filepath.Base(record.Path))
	}

	return out.String()
}
