package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/vriesdemichael/bitbucket-data-center-cli/internal/cli"
)

func main() {
	outputPath := flag.String("out", "docs/site/reference/commands/index.md", "Path to generated Markdown command reference")
	flag.Parse()

	if err := exportCommandReference(*outputPath); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func exportCommandReference(outputPath string) error {
	root := cli.NewRootCommand()
	commands := collectVisibleCommands(root)

	sort.Slice(commands, func(i, j int) bool {
		return commands[i].CommandPath() < commands[j].CommandPath()
	})

	var content strings.Builder
	// One page carrying 299 commands matches almost any query, so at the default
	// weight it crowds out the page that answers the question. Nudged just below
	// default rather than down with the ADRs: this is reference a reader does
	// want, only not ahead of the cheatsheet.
	content.WriteString("---\nsearch:\n  boost: 0.7\n---\n\n")
	content.WriteString("# All Commands\n\n")
	content.WriteString("This page is generated by `task docs:export-command-reference`. Do not edit manually.\n\n")
	content.WriteString(fmt.Sprintf("Generated command entries: %d\n\n", len(commands)))

	if globals := globalFlagsBlock(commands); globals != "" {
		// Identical for every command, and repeating it in full was roughly 40%
		// of this page. Once here and expanded, so a browser search for a global
		// flag lands on this copy instead of cycling through one per command.
		content.WriteString("## Global flags\n\n")
		content.WriteString("Accepted by every command. Each entry below repeats them in a collapsed block; this copy stays open so a page search lands here.\n\n")
		content.WriteString("```text\n")
		content.WriteString(globals)
		content.WriteString("```\n\n")
	}

	for _, command := range commands {
		helpText, err := renderHelp(command)
		if err != nil {
			return fmt.Errorf("render help for %q: %w", command.CommandPath(), err)
		}

		content.WriteString(fmt.Sprintf("## `%s`\n\n", command.CommandPath()))
		if short := strings.TrimSpace(command.Short); short != "" {
			content.WriteString(short)
			content.WriteString("\n\n")
		}

		specific, globals := splitGlobalFlags(helpText)

		content.WriteString("```text\n")
		content.WriteString(specific)
		if !strings.HasSuffix(specific, "\n") {
			content.WriteString("\n")
		}
		content.WriteString("```\n\n")

		// Collapsed rather than dropped: the entry still shows that the command
		// takes global flags, and they can be read without leaving it.
		if globals != "" {
			content.WriteString("??? note \"Global flags\"\n\n")
			content.WriteString("    ```text\n")
			for _, line := range strings.Split(strings.TrimRight(globals, "\n"), "\n") {
				content.WriteString("    " + line + "\n")
			}
			content.WriteString("    ```\n\n")
		}
	}

	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return fmt.Errorf("create command docs directory: %w", err)
	}

	payload := strings.TrimRight(content.String(), "\n") + "\n"
	if err := os.WriteFile(outputPath, []byte(payload), 0o644); err != nil {
		return fmt.Errorf("write command docs: %w", err)
	}

	fmt.Printf("wrote %s\n", outputPath)
	return nil
}

func collectVisibleCommands(root *cobra.Command) []*cobra.Command {
	commands := []*cobra.Command{root}

	var walk func(command *cobra.Command)
	walk = func(command *cobra.Command) {
		for _, child := range command.Commands() {
			if child.Hidden || cobraBuiltin[child.Name()] {
				continue
			}
			commands = append(commands, child)
			walk(child)
		}
	}

	walk(root)
	return commands
}

func renderHelp(command *cobra.Command) (string, error) {
	var buffer bytes.Buffer
	command.SetOut(&buffer)
	command.SetErr(&buffer)

	if err := command.Help(); err != nil {
		return "", err
	}

	return strings.TrimRight(buffer.String(), "\n"), nil
}

// cobraBuiltin names the commands Cobra supplies rather than this project.
//
// bb installs them eagerly so they answer --describe like everything else, which
// also puts them in the tree this exporter walks. They are shell plumbing and
// help text rather than part of the documented surface, and their help pages are
// generated by Cobra from a template, so the reference does not carry them.
var cobraBuiltin = map[string]bool{"help": true, "completion": true}

// globalFlagsMarker is the heading Cobra writes above the inherited flags.
const globalFlagsMarker = "Global Flags:"

// splitGlobalFlags separates a command's own help from the inherited flags
// every command shares.
// splitGlobalFlags separates a command's own help from the inherited flags
// every command shares.
//
// The globals run from the heading to the first blank line and no further:
// Cobra prints a trailing "Use ... --help" footer after them for any command
// with subcommands, and that line belongs to the command rather than to the
// shared block. Taking everything after the heading swept it into the shared
// copy, where it also left the block without a closing newline -- which put
// the page's own fence at the end of a text line and made the whole document
// read as one unterminated code block.
func splitGlobalFlags(helpText string) (specific, globals string) {
	index := strings.Index(helpText, globalFlagsMarker)
	if index < 0 {
		return helpText, ""
	}

	rest := helpText[index:]
	stop := strings.Index(rest, "\n\n")
	trailer := ""
	if stop >= 0 {
		trailer = rest[stop+1:]
		rest = rest[:stop]
	}

	specific = strings.TrimRight(helpText[:index], "\n") + "\n"
	if trimmed := strings.TrimSpace(trailer); trimmed != "" {
		specific += "\n" + trimmed + "\n"
	}

	return specific, strings.TrimRight(rest, "\n") + "\n"
}

// globalFlagsBlock returns the shared block once, read from the first command
// that has one so the canonical copy and the per-command copies cannot differ.
func globalFlagsBlock(commands []*cobra.Command) string {
	for _, command := range commands {
		helpText, err := renderHelp(command)
		if err != nil {
			continue
		}
		if _, globals := splitGlobalFlags(helpText); globals != "" {
			return globals
		}
	}

	return ""
}
