// Command cli-docs-export writes the command reference from the Cobra command
// tree: an index of every command, and one page per top-level command.
//
// Everything on those pages is read from the commands themselves -- the
// description, the usage line, the flags, the examples, what --dry-run checks
// and the document --json prints -- so a page is a projection of the tree
// rather than a second copy of it, and docs:verify-generated fails when the two
// disagree.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/vriesdemichael/bitbucket-data-center-cli/internal/cli"
)

func main() {
	outputDir := flag.String("out", "docs/site/reference/commands", "Directory the generated command reference pages are written to")
	flag.Parse()

	if err := exportCommandReference(*outputDir); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

// indexPage is the file name of the page listing every command.
const indexPage = "index.md"

// exportCommandReference writes the reference into outputDir and removes any
// page there it did not write.
//
// A top-level command that is renamed or removed would otherwise leave its page
// behind, still published and describing a command that no longer exists.
func exportCommandReference(outputDir string) error {
	pages, err := renderReference(cli.NewRootCommand())
	if err != nil {
		return err
	}

	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return fmt.Errorf("create command docs directory: %w", err)
	}

	for name, content := range pages {
		if err := os.WriteFile(filepath.Join(outputDir, name), []byte(content), 0o644); err != nil {
			return fmt.Errorf("write command docs: %w", err)
		}
	}

	existing, err := filepath.Glob(filepath.Join(outputDir, "*.md"))
	if err != nil {
		return fmt.Errorf("list command docs: %w", err)
	}
	for _, path := range existing {
		if _, written := pages[filepath.Base(path)]; written {
			continue
		}
		if err := os.Remove(path); err != nil {
			return fmt.Errorf("remove stale command docs: %w", err)
		}
	}

	fmt.Printf("wrote %d pages to %s\n", len(pages), outputDir)
	return nil
}

// renderReference returns every page of the reference, keyed by file name.
func renderReference(root *cobra.Command) (map[string]string, error) {
	tops := visibleCommands(root, 1)

	pages := map[string]string{
		indexPage:       indexOf(root, tops),
		globalFlagsPage: globalFlagsOf(flagsOf(root.PersistentFlags(), nil)),
	}
	for _, top := range tops {
		// A command named for one of the two pages that are not a command's
		// would take its file, and the page it replaced would go unnoticed.
		if _, taken := pages[pageName(top)]; taken {
			return nil, fmt.Errorf("the page of %q would overwrite %s", top.command.CommandPath(), pageName(top))
		}

		page, err := groupPage(root, top)
		if err != nil {
			return nil, err
		}
		pages[pageName(top)] = page
	}

	return pages, nil
}

// node is one visible command and the visible commands beneath it.
type node struct {
	command *cobra.Command
	// path is the command path without the root: "pr comment add".
	path string
	// depth counts the words in path, so a top-level command has depth 1.
	depth    int
	children []*node
}

// cobraBuiltin names the commands Cobra supplies rather than this project.
//
// bb installs them eagerly so they answer --describe like everything else, which
// also puts them in the tree this exporter walks. They are shell plumbing and
// help text rather than part of the documented surface, and their help pages are
// generated by Cobra from a template, so the reference does not carry them.
var cobraBuiltin = map[string]bool{"help": true, "completion": true}

// visibleCommands returns the commands beneath parent a person can run or
// browse, sorted by name, each with its own.
func visibleCommands(parent *cobra.Command, depth int) []*node {
	var nodes []*node
	for _, child := range parent.Commands() {
		if child.Hidden || cobraBuiltin[child.Name()] {
			continue
		}
		nodes = append(nodes, &node{
			command:  child,
			path:     strings.TrimPrefix(child.CommandPath(), parent.Root().Name()+" "),
			depth:    depth,
			children: visibleCommands(child, depth+1),
		})
	}

	sort.Slice(nodes, func(i, j int) bool { return nodes[i].path < nodes[j].path })
	return nodes
}

// runnable reports whether the node is a command a person runs, rather than a
// group that only holds others or a help topic.
func (n *node) runnable() bool {
	return n.command.Runnable()
}

// walk visits the node and everything beneath it, parents first.
func (n *node) walk(visit func(*node)) {
	visit(n)
	for _, child := range n.children {
		child.walk(visit)
	}
}

// commands returns the runnable commands beneath the node, in path order.
func (n *node) commands() []*node {
	var found []*node
	for _, child := range n.children {
		child.walk(func(each *node) {
			if each.runnable() {
				found = append(found, each)
			}
		})
	}

	return found
}

// pageName is the file a top-level command's page is written to.
func pageName(top *node) string {
	return top.command.Name() + ".md"
}

// anchor is the id Markdown gives a command's heading.
//
// The heading is the command path, and the toc extension slugs that to the
// path with its spaces as hyphens. The index carries the same id for every
// command, so a link to reference/commands/#bb-pr-merge lands on the row that
// leads to the command's own page.
func anchor(path string) string {
	return "bb-" + strings.ReplaceAll(path, " ", "-")
}
