package main

import (
	"fmt"
	"html"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
	"github.com/vriesdemichael/bitbucket-data-center-cli/internal/cli"
	"github.com/vriesdemichael/bitbucket-data-center-cli/internal/cli/outline"
)

// frontMatter opens every page.
//
// The boost sits just below default. Every command's name and description are
// on these pages, so at the default weight they match almost any query and
// crowd out the guide that answers the question. It is not lowered as far as
// the ADRs: this is reference a reader does want, only not ahead of the
// cheatsheet.
//
// The comment tells someone opening the file where it comes from without
// putting a note to contributors in front of readers. It sits in the front
// matter because MkDocs takes a page's title from its heading only when the
// heading is the first thing in the body.
const frontMatter = "---\n" +
	"# Generated by `task docs:export-command-reference` from the command tree. Do not edit.\n" +
	"search:\n  boost: 0.7\n---\n\n"

// globalFlagsPage is the file listing the flags every command takes, and
// globalFlagsAnchor the id the index keeps for them.
const (
	globalFlagsPage   = "global-flags.md"
	globalFlagsAnchor = "global-flags"
)

// maxHeadingLevel is the deepest heading a command gets. The deepest commands
// sit six words down, and a heading level per word would run out of levels and
// of contrast between them well before that.
const maxHeadingLevel = 4

// groupPage is the page of one top-level command: the command itself, and every
// command beneath it under a heading of its own.
func groupPage(root *cobra.Command, top *node) (string, error) {
	var page strings.Builder
	page.WriteString(frontMatter)
	fmt.Fprintf(&page, "# bb %s\n\n", top.path)

	commands := top.commands()
	if err := writeEntry(&page, root, top); err != nil {
		return "", err
	}

	if len(commands) > 0 {
		fmt.Fprintf(&page, "%s.\n\n", counted(len(commands), "command"))
		writeChildren(&page, top)
	}

	for _, child := range top.children {
		var failure error
		child.walk(func(each *node) {
			if failure != nil {
				return
			}
			fmt.Fprintf(&page, "%s `bb %s`\n\n", strings.Repeat("#", min(each.depth, maxHeadingLevel)), each.path)
			failure = writeEntry(&page, root, each)

			// A group one level down lists everything beneath it, so a reader
			// who opened the section sees what it holds before scrolling
			// through it. Deeper groups sit inside that list already.
			if failure == nil && each.depth == 2 && len(each.children) > 0 {
				writeDescendants(&page, each)
			}
		})
		if failure != nil {
			return "", failure
		}
	}

	return strings.TrimRight(page.String(), "\n") + "\n", nil
}

// indexOf is the page listing every command: each top-level command with its
// page, then every command on one line, so that a search of the one page
// covers the whole tool.
func indexOf(root *cobra.Command, tops []*node) string {
	var page strings.Builder
	page.WriteString(frontMatter)
	page.WriteString("# All Commands\n\n")

	total := 0
	for _, top := range tops {
		top.walk(func(each *node) {
			if each.runnable() {
				total++
			}
		})
	}
	// The id keeps a link to reference/commands/#global-flags working: it
	// lands on the sentence that leads to the page.
	fmt.Fprintf(&page, "%s, on a page per top-level command. %sEach also takes the [global flags](%s).\n\n",
		counted(total, "command"), emptyAnchor(globalFlagsAnchor), globalFlagsPage)

	for _, top := range tops {
		link := fmt.Sprintf("[`bb %s`](%s)", top.path, pageName(top))
		if len(top.children) == 0 {
			// A command with nothing beneath it has no section further down,
			// so its row here is where its id goes.
			link = idOf(top.path) + link
		}
		writeItem(&page, link, summary(top))
	}

	page.WriteString("## Every command\n\n")
	for _, top := range tops {
		if len(top.children) == 0 {
			continue
		}
		fmt.Fprintf(&page, "### `bb %s`\n\n", top.path)

		// A group has no row of its own, so its id goes on the first command
		// beneath it.
		pending := ""
		for _, child := range top.children {
			child.walk(func(each *node) {
				pending += idOf(each.path)
				if !each.runnable() {
					return
				}
				link := fmt.Sprintf("%s[`%s`](%s#%s)", pending, each.path, pageName(top), anchor(each.path))
				writeItem(&page, link, inline(each.command.Short))
				pending = ""
			})
		}
	}

	page.WriteString("## `bb`\n\n")
	writeParagraph(&page, inline(root.Short))
	page.WriteString(prose(descriptionOf(root)))
	writeFlags(&page, flagsOf(root.LocalFlags(), func(each *pflag.Flag) bool {
		return root.PersistentFlags().Lookup(each.Name) == each
	}))

	return strings.TrimRight(page.String(), "\n") + "\n"
}

// idOf is an empty anchor carrying a command's id, for a page where the
// command has no heading.
func idOf(path string) string {
	return emptyAnchor(anchor(path))
}

// emptyAnchor is an element that shows nothing and gives a link somewhere to
// land.
func emptyAnchor(id string) string {
	return fmt.Sprintf(`<a id="%s"></a>`, id)
}

// counted is a number with its noun, plural unless there is one.
func counted(count int, noun string) string {
	if count == 1 {
		return fmt.Sprintf("1 %s", noun)
	}

	return fmt.Sprintf("%d %ss", count, noun)
}

// summary is what a list says of a command: its description, and for a group
// how many commands it holds.
func summary(n *node) string {
	text := inline(n.command.Short)
	if commands := n.commands(); len(commands) > 0 {
		text += fmt.Sprintf(" (%s)", counted(len(commands), "command"))
	}

	return text
}

// writeChildren lists the commands directly beneath a node.
func writeChildren(page *strings.Builder, parent *node) {
	for _, child := range parent.children {
		writeItem(page, fmt.Sprintf("[`bb %s`](#%s)", child.path, anchor(child.path)), summary(child))
	}
}

// writeDescendants lists every command beneath a group, named from the group
// down.
func writeDescendants(page *strings.Builder, group *node) {
	for _, each := range group.commands() {
		name := strings.TrimPrefix(each.path, group.path+" ")
		writeItem(page, fmt.Sprintf("[`%s`](#%s)", name, anchor(each.path)), inline(each.command.Short))
	}
}

// writeItem writes one term and its definition.
//
// A definition list rather than a table: on a narrow screen a table scrolls
// sideways and a list stacks, and the stylesheet sets the list in two columns
// where there is room for them.
func writeItem(page *strings.Builder, term, definition string) {
	fmt.Fprintf(page, "%s\n:   %s\n\n", term, definition)
}

func writeParagraph(page *strings.Builder, text string) {
	if text != "" {
		page.WriteString(text + "\n\n")
	}
}

// writeEntry writes what the reference says of one command, in the order a
// reader needs it: what it does, how it is called, the detail, examples, flags,
// what a dry run checks and what it prints.
func writeEntry(page *strings.Builder, root *cobra.Command, n *node) error {
	command := n.command
	writeParagraph(page, inline(command.Short))

	if len(command.Aliases) > 0 {
		aliases := make([]string, len(command.Aliases))
		for index, alias := range command.Aliases {
			aliases[index] = fmt.Sprintf("`%s %s`", command.Parent().CommandPath(), alias)
		}
		writeParagraph(page, "Aliases: "+strings.Join(aliases, ", "))
	}

	if n.runnable() {
		fmt.Fprintf(page, "```text\n%s\n```\n\n", command.UseLine())
	}

	page.WriteString(prose(descriptionOf(command)))

	// A shell block, so that docs-lint checks each example against the command
	// tree like any other documented invocation.
	if example := dedent(strings.Trim(command.Example, "\n")); example != "" {
		fmt.Fprintf(page, "```bash\n%s\n```\n\n", example)
	}

	if !n.runnable() {
		return nil
	}

	writeCommandFlags(page, root, command)

	if line := cli.DryRunHelp(command); line != "" {
		writeParagraph(page, "**Dry run:** "+inline(line))
	}

	return writeOutput(page, n.path)
}

// descriptionOf is a command's long description without the short one it
// usually opens with, which the entry has already printed.
func descriptionOf(command *cobra.Command) string {
	long := strings.TrimSpace(command.Long)
	short := strings.TrimSpace(command.Short)
	if long == short {
		return ""
	}

	for _, opening := range []string{short + ".\n\n", short + "\n\n"} {
		if rest, found := strings.CutPrefix(long, opening); found {
			return rest
		}
	}

	return long
}

// writeOutput writes the document a command prints under --json: the fields of
// its data as --describe outlines them, or why it has none to outline.
//
// The outline is collapsed and kept out of the search index. A pull request
// command returns the whole pull request, so indexed, its entry would match
// every word in one -- merge, draft, reviewer -- and a search for any of them
// would return every such command ahead of the one that does it.
func writeOutput(page *strings.Builder, path string) error {
	schema, reason, declared := cli.DataSchema(path)
	if !declared {
		writeParagraph(page, "**Output with `--json`:** "+inline(reason))
		return nil
	}

	var fields strings.Builder
	if err := outline.Write(&fields, outline.Member{Name: "data", Schema: schema}); err != nil {
		return fmt.Errorf("outline the output of %q: %w", path, err)
	}

	page.WriteString("<details class=\"note\" data-search-exclude>\n")
	page.WriteString("<summary>Output with <code>--json</code>, where <code>?</code> marks a field that can be absent</summary>\n")
	fmt.Fprintf(page, "<pre><code>%s\n</code></pre>\n</details>\n\n", html.EscapeString(strings.TrimRight(fields.String(), "\n")))

	return nil
}

// globalFlagsOf is the page of the flags every command takes.
//
// One page, rather than a list on every page or under every command. The flags
// are the same wherever they are printed, so a copy per command would nearly
// double the longest pages, and a copy per page would answer a search for any
// one of them with the same list two dozen times. What a global flag does that
// differs by command is in the command's entry: what --dry-run checks, and
// what --json prints.
func globalFlagsOf(globals []flagLine) string {
	var page strings.Builder
	page.WriteString(frontMatter)
	page.WriteString("# Global flags\n\n")
	fmt.Fprintf(&page, "%s, accepted by every command.\n\n", counted(len(globals), "flag"))
	writeFlags(&page, globals)

	return strings.TrimRight(page.String(), "\n") + "\n"
}

// flagLine is one flag as help prints it: its names and value, and its usage
// with the default.
type flagLine struct {
	name  string
	usage string
}

func writeFlags(page *strings.Builder, flags []flagLine) {
	for _, each := range flags {
		writeItem(page, "`"+each.name+"`", inline(each.usage))
	}
}

// inheritedFlags are the flags a command takes from one group above it.
type inheritedFlags struct {
	// from is the group that declares them.
	from  *cobra.Command
	flags []flagLine
}

// commandFlags are the flags an entry lists, by where they come from: the
// command's own, then those of each group above it, nearest first.
//
// Cobra's help prints the second kind under "Global Flags", beside the ones
// every command takes, but --repo on bb pr or --filter on bb tag is no more
// global than a flag of the command's own, and help does not say which group
// it belongs to. The root's persistent flags are left out: every command takes
// those, and each page lists them once.
func commandFlags(root, command *cobra.Command) (own []flagLine, inherited []inheritedFlags) {
	own = flagsOf(command.LocalFlags(), func(each *pflag.Flag) bool {
		return root.PersistentFlags().Lookup(each.Name) == each
	})

	for group := command.Parent(); group != nil && group != root; group = group.Parent() {
		// The flag a command inherits under a name is the nearest group's, so
		// a name two groups declare is listed for the one that supplies it.
		flags := flagsOf(command.InheritedFlags(), func(each *pflag.Flag) bool {
			return group.PersistentFlags().Lookup(each.Name) != each
		})
		if len(flags) > 0 {
			inherited = append(inherited, inheritedFlags{from: group, flags: flags})
		}
	}

	return own, inherited
}

// writeCommandFlags lists a command's flags under where each comes from, so an
// entry says which are its own, which its group gives it, and that the global
// ones apply as well.
func writeCommandFlags(page *strings.Builder, root, command *cobra.Command) {
	own, inherited := commandFlags(root, command)
	writeFlags(page, own)

	for _, each := range inherited {
		path := strings.TrimPrefix(each.from.CommandPath(), root.Name()+" ")
		fmt.Fprintf(page, "Inherited from [`%s`](#%s):\n\n", each.from.CommandPath(), anchor(path))
		writeFlags(page, each.flags)
	}

	fmt.Fprintf(page, "Also takes the [global flags](%s).\n\n", globalFlagsPage)
}

// flagSeparator is what pflag puts between a flag and its usage when the flag
// is the only one in its set.
const flagSeparator = "   "

// flagsOf returns the flags of a set a person can pass, except --help and any
// that skip names.
//
// Each is rendered by pflag in a set of its own and split where pflag put the
// column gap, rather than put together here from the flag's fields: how a value
// is named and when a default is printed are pflag's rules, and a second
// implementation of them would drift from what --help prints.
func flagsOf(set *pflag.FlagSet, skip func(*pflag.Flag) bool) []flagLine {
	var flags []flagLine
	set.VisitAll(func(each *pflag.Flag) {
		if each.Hidden || each.Name == "help" || (skip != nil && skip(each)) {
			return
		}

		alone := pflag.NewFlagSet(each.Name, pflag.ContinueOnError)
		alone.AddFlag(each)
		line := strings.TrimSpace(alone.FlagUsagesWrapped(0))

		name, usage, _ := strings.Cut(line, flagSeparator)
		flags = append(flags, flagLine{name: name, usage: strings.TrimSpace(usage)})
	})

	return flags
}

// prose turns a long description into Markdown.
//
// Help text is written for a terminal: paragraphs wrapped by hand, and anything
// indented meant to be read as typed. A paragraph is joined into one line and
// escaped, so that Markdown wraps it to the page and reads none of it as
// markup; a run of indented lines becomes a code block.
func prose(long string) string {
	var out strings.Builder
	for _, block := range strings.Split(strings.Trim(long, "\n"), "\n\n") {
		var paragraph, code []string
		flush := func() {
			if len(paragraph) > 0 {
				out.WriteString(inline(strings.Join(paragraph, " ")) + "\n\n")
				paragraph = nil
			}
			if len(code) > 0 {
				fmt.Fprintf(&out, "```text\n%s\n```\n\n", dedent(strings.Join(code, "\n")))
				code = nil
			}
		}

		for _, line := range strings.Split(block, "\n") {
			switch {
			case strings.TrimSpace(line) == "":
				continue
			case strings.HasPrefix(line, " ") || strings.HasPrefix(line, "\t"):
				if len(paragraph) > 0 {
					flush()
				}
				code = append(code, line)
			default:
				if len(code) > 0 {
					flush()
				}
				paragraph = append(paragraph, strings.TrimSpace(line))
			}
		}
		flush()
	}

	return out.String()
}

// markdownEscapes are the characters Markdown or HTML would read as markup in
// running text, each with what prints it literally.
var markdownEscapes = strings.NewReplacer(
	`\`, `\\`,
	"`", "\\`",
	`*`, `\*`,
	`_`, `\_`,
	`[`, `\[`,
	`]`, `\]`,
	`&`, `&amp;`,
	`<`, `&lt;`,
	`>`, `&gt;`,
)

// blockMarkers open a Markdown block when a line starts with one: a list, a
// heading, a quote, a definition.
var blockMarkers = []string{"- ", "+ ", "# ", "> ", ": "}

// inline escapes one line of help text for Markdown.
//
// Text between a pair of backticks stays a code span, which is what its author
// meant and how it would read in the terminal too. Anything else that Markdown
// would take for markup is escaped, a placeholder such as <pr-id> above all,
// which would otherwise vanish as an unknown HTML tag.
func inline(text string) string {
	text = strings.TrimSpace(text)
	parts := strings.Split(text, "`")

	var out strings.Builder
	if len(parts)%2 == 0 {
		// An odd number of backticks: none of them opens a span that closes.
		out.WriteString(markdownEscapes.Replace(text))
	} else {
		for index, part := range parts {
			if index%2 == 1 {
				out.WriteString("`" + part + "`")
				continue
			}
			out.WriteString(markdownEscapes.Replace(part))
		}
	}

	escaped := out.String()
	for _, marker := range blockMarkers {
		if strings.HasPrefix(escaped, marker) {
			return `\` + escaped
		}
	}

	return escaped
}

// dedent removes the indentation every line of a block shares.
func dedent(block string) string {
	lines := strings.Split(block, "\n")
	shared := -1
	for _, line := range lines {
		if strings.TrimSpace(line) == "" {
			continue
		}
		indent := len(line) - len(strings.TrimLeft(line, " \t"))
		if shared < 0 || indent < shared {
			shared = indent
		}
	}

	for index, line := range lines {
		if len(line) >= shared && shared > 0 {
			lines[index] = line[shared:]
		}
		lines[index] = strings.TrimRight(lines[index], " \t")
	}

	return strings.Join(lines, "\n")
}
