// Command openapi-operation-paths records which endpoint each generated
// operation we call actually targets.
//
// oapi-codegen derives Go method names from operationIds, and Bitbucket ships
// many colliding ones. The sanitizer resolves a collision by appending a
// counter in spec order, which is deterministic for a given spec but not stable
// across spec versions: an operation Atlassian adds upstream shifts every later
// suffix. Delete7 was the repository reviewer-group delete in Bitbucket 10.2 and
// is a different endpoint in 10.4, and the same renumbering moved getStatus
// during the 10.2 bump.
//
// Both times the arity happened to change too, so the compiler caught it. That
// is luck, not a guarantee: two endpoints with the same shape would have
// silently swapped, and the CLI would have called the wrong URL.
//
// This tool writes the operation-to-endpoint mapping for every generated
// operation the project calls. The file is committed, so a spec bump that
// re-points one of them shows up as a reviewable diff instead of a surprise.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

type operation struct {
	Method string `json:"method"`
	Path   string `json:"path"`
}

type report struct {
	Version    int                  `json:"version"`
	Note       string               `json:"note"`
	Operations map[string]operation `json:"operations"`
}

const reportNote = "Generated by tools/openapi-operation-paths. Each entry is a generated operation this " +
	"project calls, and the endpoint it targets. A diff here on a spec bump means an operation name now " +
	"points at a different URL; confirm every call site still means what it says before accepting it."

// callRE finds generated operations invoked through the typed client, which is
// how nearly every call site in this project reaches one.
var callRE = regexp.MustCompile(`\.([A-Z][A-Za-z0-9]*)WithResponse\(`)

// rawCallRE finds the few call sites that use the raw client method instead of
// its WithResponse wrapper, which read `.CreateComment2WithBody(` rather than
// `.CreateComment2WithBodyWithResponse(`.
//
// comment.Service.Create is the reason: the wrapper decodes a 201 straight into
// the generated model, and an inline comment comes back with an anchor path the
// model cannot hold, so the body has to be read before it is parsed. Those
// operations target real endpoints and have to stay under this guard like any
// other — a call site that drops out of the report is one a spec bump can
// silently retarget.
var rawCallRE = regexp.MustCompile(`\.([A-Z][A-Za-z0-9]*WithBody)\(`)

// bareCallRE finds a raw client method called with no suffix at all, such as
// `.client.GetComments(` or `.client.UpdateComment(`.
//
// Anchored on the receiver, not just the method name. Every generated call in
// this project goes through a field named client, and the operation names are
// ordinary words -- Create, Update, Merge, Read, Watch -- that this project's
// own services also use. Matching on the name alone recorded twenty-two
// operations nothing calls, which is worse than the gap it closed: a spec bump
// would then diff an operation no call site has, and a reader who learns the
// report cries wolf stops reading it.
//
// A match still only counts when the generated client declares the name, so a
// field called client on some other type cannot smuggle one in.
//
// comment.Service is why this exists: its listings and single reads take the
// raw method so an anchor path can be repaired before decoding (ADR-077). Six
// operations dropped out of this report when they did, which is exactly the
// silent retargeting the report exists to prevent.
var bareCallRE = regexp.MustCompile(`\.client\.([A-Z][A-Za-z0-9]*)\(`)

func main() {
	generated := flag.String("generated", filepath.Join("internal", "openapi", "generated", "bitbucket_client.gen.go"), "Generated OpenAPI client")
	sourceRoot := flag.String("source", ".", "Root to scan for call sites")
	out := flag.String("out", filepath.Join("docs", "quality", "generated-operation-paths.json"), "Report to write")
	verify := flag.Bool("verify", false, "Fail if the committed report is out of date instead of writing it")
	flag.Parse()

	operations, err := parseOperations(*generated)
	if err != nil {
		fail(err)
	}

	called, err := collectCalledOperations(*sourceRoot, *generated, operations)
	if err != nil {
		fail(err)
	}

	result := report{Version: 1, Note: reportNote, Operations: map[string]operation{}}
	var unknown []string
	for name := range called {
		op, ok := operations[name]
		if !ok {
			// A call to something the generated client does not define cannot
			// compile, so this only fires on a stale scan; surface it anyway.
			unknown = append(unknown, name)
			continue
		}
		result.Operations[name] = op
	}
	if len(unknown) > 0 {
		sort.Strings(unknown)
		fail(fmt.Errorf("call sites reference operations absent from the generated client: %s", strings.Join(unknown, ", ")))
	}

	encoded, err := json.MarshalIndent(result, "", "  ")
	if err != nil {
		fail(err)
	}
	encoded = append(encoded, '\n')

	if *verify {
		existing, readErr := os.ReadFile(*out)
		if readErr != nil {
			fail(fmt.Errorf("read %s: %w\n\nWrite it with: task openapi:operation-paths", *out, readErr))
		}
		if string(existing) != string(encoded) {
			fail(fmt.Errorf("%s is out of date.\n\nAn operation this project calls may now target a different endpoint.\nRegenerate with: task openapi:operation-paths\nThen read the diff and confirm every changed call site still means what it says", *out))
		}
		fmt.Printf("generated operation paths are current (%d operations)\n", len(result.Operations))
		return
	}

	if err := os.MkdirAll(filepath.Dir(*out), 0o755); err != nil {
		fail(err)
	}
	if err := os.WriteFile(*out, encoded, 0o644); err != nil {
		fail(err)
	}
	fmt.Printf("wrote %s (%d operations)\n", *out, len(result.Operations))
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err.Error())
	os.Exit(1)
}

// parseOperations reads each NewXxxRequest constructor in the generated client
// and recovers the endpoint it builds. The generator emits a fixed shape:
// the HTTP method is a string literal passed to http.NewRequest, and the path
// is assigned to operationPath, either from a literal or a fmt.Sprintf format.
func parseOperations(generatedPath string) (map[string]operation, error) {
	fileSet := token.NewFileSet()
	parsed, err := parser.ParseFile(fileSet, generatedPath, nil, 0)
	if err != nil {
		return nil, fmt.Errorf("parse %s: %w", generatedPath, err)
	}

	operations := map[string]operation{}
	for _, decl := range parsed.Decls {
		function, ok := decl.(*ast.FuncDecl)
		if !ok || function.Recv != nil {
			continue
		}
		operationName, ok := operationFromConstructor(function.Name.Name)
		if !ok {
			continue
		}

		// An operation that takes a body gets two constructors. The typed one
		// marshals and delegates, so only the WithBody variant carries the
		// endpoint; whichever yields it wins.
		path, method := extractEndpoint(function)
		if path == "" || method == "" {
			continue
		}
		operations[operationName] = operation{Method: method, Path: path}
	}

	if len(operations) == 0 {
		return nil, fmt.Errorf("no operations found in %s", generatedPath)
	}

	return operations, nil
}

// bodyConstructorSuffixes are the request-body variants oapi-codegen emits
// alongside the plain constructor, longest first so trimming is unambiguous.
var bodyConstructorSuffixes = []string{
	"WithApplicationVndAtlBitbucketBulkPlusJSONBody",
	"WithBody",
}

// trimBodySuffix removes the request-body marker oapi-codegen appends to the
// constructor and client method names for operations that take one.
func trimBodySuffix(name string) string {
	for _, suffix := range bodyConstructorSuffixes {
		if strings.HasSuffix(name, suffix) {
			return strings.TrimSuffix(name, suffix)
		}
	}
	return name
}

// operationFromConstructor recovers the operation name from a generated request
// constructor: NewCreateProjectRequestWithBody and NewCreateProjectRequest both
// describe CreateProject.
func operationFromConstructor(name string) (string, bool) {
	if !strings.HasPrefix(name, "New") {
		return "", false
	}
	trimmed := trimBodySuffix(strings.TrimPrefix(name, "New"))

	if !strings.HasSuffix(trimmed, "Request") {
		return "", false
	}
	trimmed = strings.TrimSuffix(trimmed, "Request")
	if trimmed == "" {
		return "", false
	}

	return trimmed, true
}

func extractEndpoint(function *ast.FuncDecl) (path string, method string) {
	ast.Inspect(function.Body, func(node ast.Node) bool {
		switch typed := node.(type) {
		case *ast.AssignStmt:
			if path != "" {
				return true
			}
			for i, lhs := range typed.Lhs {
				ident, ok := lhs.(*ast.Ident)
				if !ok || ident.Name != "operationPath" || i >= len(typed.Rhs) {
					continue
				}
				path = staticString(typed.Rhs[i])
			}
		case *ast.CallExpr:
			if method != "" {
				return true
			}
			selector, ok := typed.Fun.(*ast.SelectorExpr)
			if !ok || selector.Sel.Name != "NewRequest" {
				return true
			}
			if len(typed.Args) == 0 {
				return true
			}
			method = staticString(typed.Args[0])
		}
		return true
	})

	return path, method
}

// staticString recovers a string constant, resolving the fmt.Sprintf form the
// generator uses for paths with parameters down to its format string.
func staticString(expr ast.Expr) string {
	switch typed := expr.(type) {
	case *ast.BasicLit:
		if typed.Kind != token.STRING {
			return ""
		}
		unquoted, err := strconv.Unquote(typed.Value)
		if err != nil {
			return ""
		}
		return unquoted
	case *ast.CallExpr:
		selector, ok := typed.Fun.(*ast.SelectorExpr)
		if !ok || selector.Sel.Name != "Sprintf" || len(typed.Args) == 0 {
			return ""
		}
		return staticString(typed.Args[0])
	}
	return ""
}

// skipDirectory reports whether a directory is outside this checkout's own
// source.
//
// Dot-directories are the load-bearing case and the reason this is a function.
// Agent tooling keeps full checkouts of other branches under .claude/worktrees/
// -- gitignored, but still on disk and still full of .go files. Walking them
// made this tool report call sites from other branches as if they belonged to
// this one: on one machine that was 2,569 extra Go files, and the artifact was
// regenerated with 468 operations that no code on the branch actually calls.
//
// The rule is that anything git does not track is not this checkout's source.
// Skipping dot-directories covers that for .claude, .git, .idea and their kin
// without shelling out to git, and the root is reached with path "." which must
// not itself be skipped.
func skipDirectory(path, name string) bool {
	switch name {
	case ".tmp", "node_modules", "docs", "vendor":
		return true
	}
	return path != "." && strings.HasPrefix(name, ".")
}

// collectCalledOperations scans the project's own Go source for typed client
// calls, ignoring the generated client itself.
func collectCalledOperations(root, generatedPath string, declared map[string]operation) (map[string]bool, error) {
	generatedAbs, err := filepath.Abs(generatedPath)
	if err != nil {
		return nil, err
	}

	called := map[string]bool{}
	err = filepath.Walk(root, func(path string, info os.FileInfo, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if info.IsDir() {
			if skipDirectory(path, info.Name()) {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") {
			return nil
		}
		absolute, absErr := filepath.Abs(path)
		if absErr == nil && absolute == generatedAbs {
			return nil
		}

		content, readErr := os.ReadFile(path)
		if readErr != nil {
			return readErr
		}
		for _, match := range callRE.FindAllSubmatch(content, -1) {
			// A body call site reads AddWithBodyWithResponse; the operation is
			// Add, the same one the plain constructor describes.
			called[trimBodySuffix(string(match[1]))] = true
		}
		for _, match := range rawCallRE.FindAllSubmatch(content, -1) {
			called[trimBodySuffix(string(match[1]))] = true
		}
		for _, match := range bareCallRE.FindAllSubmatch(content, -1) {
			name := trimBodySuffix(string(match[1]))
			if _, isOperation := declared[name]; isOperation {
				called[name] = true
			}
		}
		return nil
	})
	if err != nil {
		return nil, err
	}

	return called, nil
}
